### ISSUE TITLE
Error on 'npm install' - Unexpected key 'output' found

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-heatmap#22]
When I run `npm install` in this repository, I get an error on the `build` portion:

```
> esri-leaflet-heatmap@2.0.0 build C:\.....\esri-leaflet-heatmap
> rollup -c profiles/debug.js & rollup -c profiles/production.js

Unexpected key 'output' found, expected one of: banner, dest, entry, exports, external, footer, format, globals, indent, intro, moduleId, moduleName, onwarn, outro, plugins, sourceMap
Error: Unexpected key 'output' found, expected one of: banner, dest, entry, exports, external, footer, format, globals, indent, intro, moduleId, moduleName, onwarn, outro, plugins, sourceMap
    at validateKeys (C:\.....\esri-leaflet-heatmap\node_modules\rollup\www\ROLLUP\rollup\src\utils\validateKeys.js:12:11)
    at Object.rollup (C:\.....\esri-leaflet-heatmap\node_modules\rollup\www\ROLLUP\rollup\src\rollup.js:39:16)
    at bundle (C:\.....\esri-leaflet-heatmap\node_modules\rollup\bin\runRollup.js:136:16)
    at execute (C:\.....\esri-leaflet-heatmap\node_modules\rollup\bin\runRollup.js:125:3)
    at C:\.....\esri-leaflet-heatmap\node_modules\rollup\bin\runRollup.js:69:4
    at tryCatch (C:\.....\esri-leaflet-heatmap\node_modules\rollup\www\ROLLUP\rollup\node_modules\es6-promise\lib\es6-promise\-internal.js:185:12)
    at invokeCallback (C:\.....\esri-leaflet-heatmap\node_modules\rollup\www\ROLLUP\rollup\node_modules\es6-promise\lib\es6-promise\-internal.js:197:13)
    at publish (C:\.....\esri-leaflet-heatmap\node_modules\rollup\www\ROLLUP\rollup\node_modules\es6-promise\lib\es6-promise\-internal.js:168:7)
    at flush (C:\.....\esri-leaflet-heatmap\node_modules\rollup\www\ROLLUP\rollup\node_modules\es6-promise\lib\es6-promise\asap.js:87:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

[Per jgravois](https://github.com/Esri/esri-leaflet-heatmap/issues/21#issuecomment-537992802):
> the error is caused by the fact that this plugin imports a base rollup.config from Esri-leaflet, which was upgraded [....] quite awhile ago.

So I think we should update our Rollup dependency in this repo to match [esri-leaflet's](https://github.com/Esri/esri-leaflet/blob/0e93672260176a54382c4764bedad2fac684a255/package.json#L35) (v0.56.5 as of this writing) (and any applicable related rollup plugins, etc)

**Comment by gavinr** [comment]
Fixed in #25
